ALTER TABLE reviews MODIFY COLUMN status ENUM('PENDING', 'APPROVED', 'REJECTED', 'VISIBLE', 'HIDDEN') NOT NULL DEFAULT 'PENDING';
UPDATE reviews SET status = 'APPROVED' WHERE status = 'VISIBLE';
UPDATE reviews SET status = 'REJECTED' WHERE status = 'HIDDEN';
ALTER TABLE reviews MODIFY COLUMN status ENUM('PENDING', 'APPROVED', 'REJECTED') NOT NULL DEFAULT 'PENDING';
